# Site settings
title: Busco Trabajo CABA 
email: buscotrabajoargentina@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio Web con ofertas de trabajo en CABA.
  
  
baseurl: "/buscotrabajoargentina.github.io" # the subpath of your site, e.g. /blog
url: "https://buscotrabajoargentina.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer




# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-140961567-1

# Comments
disqus: no
disqus-shortname: webjeda-demo

#social


email: buscotrabajoargentina@hotmail.com

#facebook like box
fb-like-box: no
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]
