---
title: Buscotrabajoargentina.Github.Io
timezone: America/Argentina/Buenos_Aires
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: minimal-mistakes
